apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  labels:
    app: sample
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
      version: green
  template:
    metadata:
      labels:
        app: sample
        version: green
    spec:
      containers:
      - name: app
        image: your-dockerhub-username/bluegreen-sample:latest
        ports:
        - containerPort: 8080
